### ISSUE TITLE
Add Coordinates filter

### ISSUE THREAD

**Issue by dolugen** [dolugen/openaq-browser#2]
Add the new `coordinates`, `radius` parameters to
- [x] Latest
- [x] Locations
- [x] Measurements pages.

**Comment by dolugen** [comment]
@jflasher Location and measurement queries by coordinates seem a bit slow. It's taking several seconds for a fresh query for me.

**Comment by jflasher** [comment]
Oh yeah? What's an example query? We may just need to create an index on coordinates, but for some reason, I thought postgis already did that.

**Comment by dolugen** [comment]
@jflasher Requests to Measurements. You can probably pick any coordinates from Locations and use it on Measurements.

Just now, I made several requests and most of them got cancelled after 10s (timeout).

Latest and Locations with coordinates seem responsive enough, though.

**Comment by jflasher** [comment]
Yep, looks like we just need to make an index on the `coordinates` field explicitly. The aggregation endpoints are handled using `turf` server side, so it makes sense they're still quick.

http://postgis.net/docs/manual-1.3/ch03.html#id434676
