### ISSUE TITLE
Cities options only show 100 items due to paging

### ISSUE THREAD

**Issue by jalbertbowden** [dolugen/openaq-browser#4]
Was just using and couldn't get the Cities select form control to show any city in the US after Carlsbad. Inspecting element just showed the options' elements ending after the one mentioned....

**Comment by jalbertbowden** [comment]
Sorry, I'm in chrome in os x

**Comment by dolugen** [comment]
Hi @jalbertbowden, I'll take a look at it, thanks!

Note: This can be seen in Latest and Measurements pages.

**Comment by dolugen** [comment]
Pushed a quick fix that maximizes the limit parameter.

@jalbertbowden Now you should get all 651 cities of US from OpenAQ!

**Comment by jalbertbowden** [comment]
thanks!
nice turn around time!
