### ISSUE TITLE
Search for country=PL returns a city called "pollutants"

### ISSUE THREAD

**Issue by tetianakh** [dolugen/openaq-browser#8]
A request to https://api.openaq.org/v1/cities?country=PL returns a list of Polish cities, among which there's this:

```{"city":"pollutants","country":"PL","locations":1,"count":66},```

Of course, there's no city "pollutants" in Poland.

**Comment by dolugen** [comment]
Hello @tetianakh, thanks for reporting this issue!

I suspect it was a temporary test entry in the Polish database and was saved into OpenAQ database before it was removed. [Looking at the records](https://api.openaq.org/v1/measurements?country=PL&city=pollutants), there were only 10 hourly data requests for the "unused" location in "pollutants" city on Jul 29 2016 and no more.

As this is not directly related to the openaq-browser, we could make an issue about this on the openaq/openaq-api project, suggesting to investigate this and possibly remove these invalid entries.

cc @jflasher

**Comment by jflasher** [comment]
Thanks for catching this @tetianakh, as @dolugen said this is definitely something with the fetching and probably points to a momentary change in page structure. I've deleted the incorrect points and actually found some more for Thailand, so fixing that up now.
